FROM centos:latest

LABEL version="0.1"
LABEL maintaner="ltreugene@gmail.com"

ADD centos_build.sh /
RUN bash -x ./centos_build.sh

VOLUME ["/data", "/scripts"]
RUN rm ./centos_build.sh
WORKDIR "/root"